server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
  forward-headers-strategy: framework
spring:
  jackson:
    mapper:
      accept-case-insensitive-enums: true

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

jwt:
  access-token:
    name: AccessToken
    secret: ${JWT_ACCESS_SECRET}
    expiration: 36000000
  refresh-token:
    name: RefreshToken
    secret: ${JWT_REFRESH_SECRET}
    expiration: 864000000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
  show-actuator: false
  packages-to-scan: com.pluxity
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

user:
  init-password: ${USER_INIT_PASSWORD}
  # Teams 자동 가입 시 허용할 회사 이메일 도메인
  allowed-email-domains:
    - pluxity.com