spring:
  profiles:
    group:
      default: common, local
      local: common, local
      stage: common, stage
      prod: common, prod

logging:
  level:
    org: INFO
    com: INFO
    root: INFO
    org.zalando.logbook: TRACE