name: Deploy (Docker)

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: weekly-report-api
  SERVER_DIR: weeklyReport

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .

      - name: Save Docker image to tar
        run: |
          docker save -o ${{ env.IMAGE_NAME }}.tar ${{ env.IMAGE_NAME }}:latest
          chmod 644 ${{ env.IMAGE_NAME }}.tar

      - name: Upload Docker image tar to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.PLX_DEV_DOMAIN }}
          username: ${{ secrets.PLX_DEV_USER }}
          password: ${{ secrets.PLX_DEV_PASSWORD }}
          port: ${{ secrets.PLX_DEV_SSH_PORT }}
          source: "${{ env.IMAGE_NAME }}.tar"
          target: "${{ secrets.DOCKER_PATH }}/${{ env.SERVER_DIR }}"

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.PLX_DEV_DOMAIN }}
          username: ${{ secrets.PLX_DEV_USER }}
          password: ${{ secrets.PLX_DEV_PASSWORD }}
          port: ${{ secrets.PLX_DEV_SSH_PORT }}
          script: |
            cd ${{ secrets.DOCKER_PATH }}/${{ env.SERVER_DIR }}
            chmod +x deploy.sh
            ./deploy.sh
